import Button from "@/components/ui/Button";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth";
import { FC } from "react";
import SignOut from "./singOut";

interface pageProps {}

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const page: FC<pageProps> = async ({}) => {
  const session = await getServerSession(authOptions);

  return (
    <>
      <pre>{JSON.stringify(session)}</pre>
      <Button type="button" className="w-full">
        ok
      </Button>
      <SignOut />
    </>
  );
};

export default page;
